#!/bin/sh
#SBATCH --job-name=hfo2md
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --partition=cpu
echo "SLURM_SUBMIT_DIR is $SLURM_SUBMIT_DIR"

echo "Starting job $SLURM_JOB_ID at " `date`

echo "Running on nodes: $SLURM_NODELIST"

module load cuda/11.8-share intel/2020

#export PATH=/data/home/wuxingxing/codespace/lammps_fortran_cc/lammps_neigh_mlff_20230508/src/:$PATH

#export PATH=/data/home/wuxingxing/codespace/lammps-MatPL/lammps-fortran-2025.3/src/:$PATH
#export LD_LIBRARY_PATH=/data/home/wuxingxing/codespace/lammps-MatPL/lammps-fortran-2025.3/src:$LD_LIBRARY_PATH

source /data/home/wuxingxing/codespace/lammps-MatPL/lammps-fortran-2025.3/env.sh


mpirun -np 4 lmp_mpi -in in.lammps

end=$(date +%s)
take=$(( end - start ))


