#!/bin/sh
#SBATCH --job-name=hfo2md
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --partition=3080ti,1080ti,3090
echo "SLURM_SUBMIT_DIR is $SLURM_SUBMIT_DIR"

echo "Starting job $SLURM_JOB_ID at " `date`

echo "Running on nodes: $SLURM_NODELIST"

module load cuda/11.8-share intel/2020

source ~/codespace/lammps-MatPL/lammps-libtorch-2025.3/env.sh 

mpirun -np 4 lmp_mpi -in in.lammps

end=$(date +%s)
take=$(( end - start ))


